### ISSUE TITLE
没有生效

### ISSUE THREAD

**Issue by wldll** [a709560839/HideNavBar#1]
![Screenshot_2023-08-31-15-07-59-594_com miui securitycenter](https://github.com/a709560839/HideNavBar/assets/45764738/a72195f3-c02b-4f3d-bb52-f7cbe60cc77a)
在这个较新的版本中失效了

**Comment by a709560839** [comment]
兄弟可以mt管理器提取下这个桌面发给我吗，发蓝奏云之类的网盘都行

**Comment by wldll** [comment]
123云盘可以么？
https://www.123pan.com/s/9tjeVv-CRAHd.html

**Comment by a709560839** [comment]
> 123云盘可以么？ https://www.123pan.com/s/9tjeVv-CRAHd.html

ok的，我看看哈

**Comment by a709560839** [comment]
兄弟，你有打开 隐藏手势提示线 这个选项吗，我装了之后切换没问题，反而发现底部点击事件有bug~
[打开这个设置](https://github.com/a709560839/HideNavBar/blob/main/screenshot/screenshot1.jpg)

**Comment by wldll** [comment]
开了，并且重启了，然后在开关提示线前后对比测试了很多下，确实没有生效

**Comment by a709560839** [comment]
> 开了，并且重启了，然后在开关提示线前后对比测试了很多下，确实没有生效

那可以说下机型和miui版本吗？或者也可以试试 米客，

**Comment by wldll** [comment]
![Screenshot_2023-08-31-16-32-29-117_com android settings](https://github.com/a709560839/HideNavBar/assets/45764738/364eb8be-e5d5-458c-a9d3-fd42854880a5)
这个是小米13pro移植版

**Comment by wldll** [comment]
![Screenshot_2023-08-31-16-34-07-154_name monwf customiuizer](https://github.com/a709560839/HideNavBar/assets/45764738/28ebc81f-4a28-44d4-a8d7-be100300436e)
米客的这个？

**Comment by a709560839** [comment]
对的

**Comment by a709560839** [comment]
怎么样，米客的可以吗

**Comment by wldll** [comment]
谢谢啦，米客的没问题

**Comment by a709560839** [comment]
> 谢谢啦，米客的没问题

OK~
